- hosts: all
  become: true
  tasks:
  - name: Install Nginx
    dnf:
      name: nginx
      state: present

  - name: Create an webpage 
    copy:
      dest: /usr/share/nginx/html/index.html
      content: "<h1>Hello, World!</h1>"

  - name: Restart Nginx
    service:
      name: nginx
      state: restarted

